---
# Generate IOS Device Sensor config
- name: Generate Device Sensor config
  ansible.builtin.template:
    src: 1x-dev-sensor.j2
    dest: "{{ role_path }}/files/sensor_{{ inventory_hostname }}.ios"

- name: Push config
  cisco.ios.ios_config:
    src: "{{ role_path }}/files/sensor_{{ inventory_hostname }}.ios"
    match: none
  when: push_config
  notify:
    - SaveConfig
