---
# Generate IOS 802.1x Global Config
- name: Generate IOS 802.1x Global Config
  ansible.builtin.template:
    src: 1x-global.j2
    dest: "{{ role_path }}/files/1xglobal_{{ inventory_hostname }}.ios"

- name: Push 1x global config
  cisco.ios.ios_config:
    src: "{{ role_path }}/files/1xglobal_{{ inventory_hostname }}.ios"
    match: none
  when: push_config
  notify:
    - SaveConfig
