---
# Generate Global IOS dot1x Config
- name: Generate Global dot1x Config
  template: src=1x-global.j2 dest=roles/{{ role_name }}/files/1xglobal_{{ inventory_hostname }}.cfg

- name: Push config
  ios_config:
    src: roles/{{ role_name }}/files/1xglobal_{{ inventory_hostname }}.cfg
    match: none
  when: push_config
  notify:
    - SaveConfig
