---
# Generate IOS Interface config
- name: Generate IOS interface config
  ansible.builtin.template:
    src: 1x-int.j2
    dest: "{{ role_path }}/files/1xint_{{ inventory_hostname }}.ios"

- name: Push Interface config
  cisco.ios.ios_config:
    src: "{{ role_path }}/files/1xint_{{ inventory_hostname }}.ios"
    match: none
  when: push_config
  notify:
    - SaveConfig
