---
# tasks file for ios-config
- name: Gather IOS facts
  ios_facts:
    gather_subset: '{{ ios_config_fact_subsets }}'
    gather_network_resources: '{{ ios_config_fact_network_resources | default(omit) }}'
  when: fact_gather_enabled

- name: Interface Config
  import_tasks: interface.yml
  when: ios_int_config_enabled

- name: Device Sensor Config
  import_tasks: 1x-dev-sensor.yml
  when: ios_sensor_config_enabled

- name: 1x Global Config
  import_tasks: 1x-global.yml
  when: ios_1xglobal_config_enabled

- name: 1x Interface Config
  import_tasks: 1x-int.yml
  when: int_global_config_enabled

- name: pnp Config
  import_tasks: pnp.yml
  when: pnp_config_enabled

- name: tacacs config
  import_tasks: tacacs.yml
  when: tacacs_config_enabled
