---
# Generate IOS PnP Config
- name: Generate PnP Config
  ansible.builtin.template:
    src: pnp.j2
    dest: "{{ role_path }}/files/{{ ansible_net_serialnum }}.cfg"

- name: Push PnP config
  cisco.ios.ios_config:
    src: "{{ role_path }}/files/sensor_{{ inventory_hostname }}.cfg"
    match: none
  when: push_config
  notify:
    - SaveConfig
