---
# Generate IOS Device Sensor config
- name: Generate PnP Config
  template: src=pnp.j2 dest=roles/ios_config/files/{{ Serial }}.cfg

- name: Push config
  ios_config:
    src: roles/ios_config/files/sensor_{{ inventory_hostname }}.cfg
    match: none
  when: push_config
  notify:
    - SaveConfig
